input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["hikari-activity"]
    codec => "json"
    auto_offset_reset => "earliest"
    group_id => "hikari-logstash-activity"
    client_id => "hikari-logstash-activity"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "hikari-activity"
  }
}
