input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["competition1"]
    codec => "json"
    auto_offset_reset => "earliest"
    group_id => "hikari-logstash"
    client_id => "hikari-logstash"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "competition1"
  }
}
