"""Downloads the Hikari typefaces so the platform stops depending on the internet.

The stylesheets used to import Inter and Space Grotesk straight from Google.
A competition venue that blocks external domains would therefore serve every
competitor a fallback system font, and each page load would reach a third party
from the competitor's browser. This script fetches the files once and writes a
stylesheet that points at the copies shipped with the artifact.

Run it whenever the typefaces or their weights change:

    python3 deploy/local/scripts/bundle_fonts.py
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path
from typing import Iterator, List

from pydantic import BaseModel


GOOGLE_STYLESHEET = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600;700"
    "&family=Space+Grotesk:wght@500;600;700"
    "&display=swap"
)

# Google answers with TTF unless the caller looks like a browser that reads
# woff2, which is roughly a third of the size.
BROWSER_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# The platform is written in Portuguese. Cyrillic, Greek and Vietnamese subsets
# would add weight that no page ever renders.
WANTED_SUBSETS = ("latin", "latin-ext")

ASSETS_DIRECTORY = Path(__file__).resolve().parents[3] / "ctfd/CTFd/plugins/hikari_plugin/assets"
FONTS_DIRECTORY = ASSETS_DIRECTORY / "fonts"
LOCAL_STYLESHEET = ASSETS_DIRECTORY / "fonts.css"


class FontFace(BaseModel):
    """One @font-face rule that will be served from the artifact itself."""

    subset: str
    family: str
    weight: int
    style: str
    unicode_range: str
    source_url: str

    @property
    def file_name(self) -> str:
        slug = self.family.lower().replace(" ", "-")
        return f"{slug}-{self.weight}-{self.subset}.woff2"

    def to_css(self) -> str:
        return (
            "@font-face {\n"
            f"    font-family: '{self.family}';\n"
            f"    font-style: {self.style};\n"
            f"    font-weight: {self.weight};\n"
            "    font-display: swap;\n"
            f"    src: url('fonts/{self.file_name}') format('woff2');\n"
            f"    unicode-range: {self.unicode_range};\n"
            "}\n"
        )


def fetch(url: str) -> bytes:
    """Read a URL, letting a failure reach the caller instead of a partial file."""
    request = urllib.request.Request(url, headers={"User-Agent": BROWSER_USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def parse_font_faces(stylesheet: str) -> Iterator[FontFace]:
    """Read the @font-face rules Google returned, keeping the wanted subsets.

    Each rule is preceded by a comment naming its subset, which is the only
    place the subset appears.
    """
    blocks = re.findall(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", stylesheet, re.S)
    for subset, body in blocks:
        if subset not in WANTED_SUBSETS:
            continue
        yield FontFace(
            subset=subset,
            family=extract(body, r"font-family: '([^']+)'"),
            weight=int(extract(body, r"font-weight: (\d+)")),
            style=extract(body, r"font-style: (\w+)"),
            unicode_range=extract(body, r"unicode-range: ([^;]+);"),
            source_url=extract(body, r"url\((https://[^)]+\.woff2)\)"),
        )


def extract(text: str, pattern: str) -> str:
    """Return the single capture of a pattern, failing loudly when absent."""
    found = re.search(pattern, text)
    if found is None:
        raise ValueError(f"Google stylesheet changed shape: no match for {pattern}")
    return found.group(1).strip()


def download_faces(faces: List[FontFace]) -> None:
    FONTS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for face in faces:
        destination = FONTS_DIRECTORY / face.file_name
        destination.write_bytes(fetch(face.source_url))
        print(f"  {face.file_name}  {destination.stat().st_size // 1024} KB")


def write_stylesheet(faces: List[FontFace]) -> None:
    header = (
        "/* Hikari typefaces, served from the artifact.\n"
        " *\n"
        " * Generated by deploy/local/scripts/bundle_fonts.py. Editing this file by\n"
        " * hand is pointless: run the script again instead.\n"
        " *\n"
        " * The platform must render identically on a network that blocks external\n"
        " * domains, which is the normal condition inside an organisation hosting a\n"
        " * competition.\n"
        " */\n\n"
    )
    LOCAL_STYLESHEET.write_text(header + "\n".join(face.to_css() for face in faces))


def main() -> None:
    stylesheet = fetch(GOOGLE_STYLESHEET).decode("utf-8")
    faces = list(parse_font_faces(stylesheet))
    if not faces:
        raise ValueError("no font faces matched the wanted subsets")

    print(f"Baixando {len(faces)} arquivo(s) de fonte:")
    download_faces(faces)
    write_stylesheet(faces)
    print(f"Folha local escrita em {LOCAL_STYLESHEET.relative_to(LOCAL_STYLESHEET.parents[4])}")


if __name__ == "__main__":
    main()
