apiVersion: v1
kind: ConfigMap
metadata:
  name: ctfd-config
  namespace: ctfd
  labels:
    app: ctfd
data:
  UPLOAD_FOLDER: /var/uploads
  DATABASE_URL: mysql+pymysql://ctfd:ctfd@ctfd-mariadb.ctfd.svc.cluster.local:3306/ctfd
  REDIS_URL: redis://ctfd-redis:6379
  WORKERS: "1"
  LOG_FOLDER: /var/log/CTFd
  REVERSE_PROXY: "True"
  PROD: "true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.elk.svc.cluster.local:9092"
  KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
  KAFKA_SASL_USERNAME: "user1"
  KAFKA_SASL_PASSWORD: "${KAFKA_SASL_PASSWORD}"
